apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.restaurant.wukong.com
spec:
  insecureSkipTLSVerify: true
  group: restaurant.wukong.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: aaserver
    namespace: restaurant
  version: v1alpha1
