kind: Endpoints
apiVersion: v1
metadata:
  name: aaserver
  namespace: restaurant
subsets:
  - addresses:
      - ip: 10.21.17.77 # replace by the local IP address
    ports:
      - port: 8443
        name: https