apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-rolebinding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-role

#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: testadminbinding
#  namespace: at-system
#subjects:
#  - kind: ServiceAccount
#    name: controller-manager
#    namespace: at-test
#roleRef:
#  kind: Role
#  name: pod-role
#  apiGroup: rbac.authorization.k8s.io