apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaserver
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: aaserver
      containers:
      - name: main-aaserver
        # build from 10_sample-apiserver/Dockerfile
        image: wukongsun/sample-apiserver:0.1
        imagePullPolicy: Never
        args: [ "--etcd-servers=http://localhost:2379" ]
        env:
          - name: GODEBUG
            value: x509sha1=1
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.4
